name: PostgreSQL Service Example
on: push

jobs:
  please-work:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Connect to PostgreSQL

        run: node client.js
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432